services:
    workspace:
        build:
            context: .
            dockerfile: Dockerfile
        volumes:
            - ..:/workspace:cached
        command: sleep infinity
    redis:
        image: esolang/sqlite3